#!/bin/bash
# Builds dashboard-standalone.html: dashboard.html with every LOCAL
# <script src="..."> inlined, so the file opens directly in Chrome with no
# server. CDN scripts (Chart.js, SheetJS) are left as-is — they need network.
#
# Generated automatically from dashboard.html — DO NOT hand-edit the output.
# Anything added to dashboard.html is picked up on the next build, so the
# standalone can no longer drift behind the live dashboard.
#
# Note: server-backed features (KV sync, AI parse) degrade gracefully to
# localStorage-only when opened as a file.

cd "$(dirname "$0")"
OUT=dashboard-standalone.html
: > "$OUT"

echo "<!-- GENERATED by build.sh from dashboard.html — do not edit by hand -->" >> "$OUT"

while IFS= read -r line; do
  if [[ $line =~ \<script\ src=\"([^\"]+)\"[^\>]*\>\</script\> ]]; then
    src="${BASH_REMATCH[1]}"
    if [[ $src == http* ]]; then
      echo "$line" >> "$OUT"            # CDN — keep the tag
    elif [[ -f $src ]]; then
      {
        echo "<script>"
        # app.js: embed sample data so loadSample() works without fetch
        if [[ $src == app.js && -f sample_vessels.json ]]; then
          echo "const SAMPLE_DATA = "
          cat sample_vessels.json
          echo ";"
          sed 's/async function loadSample() {/function loadSample() {/' app.js \
            | sed 's/const resp = await fetch.*$/\/\/ Using embedded data/' \
            | sed 's/const data = await resp.json();/const data = SAMPLE_DATA;/'
        else
          cat "$src"
        fi
        echo ""
        echo "</script>"
      } >> "$OUT"
    else
      echo "<!-- MISSING: $src -->" >> "$OUT"
      echo "WARNING: $src referenced by dashboard.html but not found" >&2
    fi
  else
    echo "$line" >> "$OUT"
  fi
done < dashboard.html

echo "Built: $OUT ($(wc -l < "$OUT") lines)"
echo "Open it directly in Chrome — no server needed."
